services:
  - type: web
    name: blockchain-medical-app
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: BLOCKCHAIN_RPC_URL
        sync: false
      - key: ACCOUNT_ADDRESS
        sync: false
      - key: PRIVATE_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_PATH
        value: users.db
